// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/Heater_dog/Vk_Intern/internal/auth"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: ctx, tokenFields
func (_m *TokenService) GenerateToken(ctx context.Context, tokenFields auth.TokenFileds) (string, string, time.Time, error) {
	ret := _m.Called(ctx, tokenFields)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 string
	var r2 time.Time
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.TokenFileds) (string, string, time.Time, error)); ok {
		return rf(ctx, tokenFields)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.TokenFileds) string); ok {
		r0 = rf(ctx, tokenFields)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.TokenFileds) string); ok {
		r1 = rf(ctx, tokenFields)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, auth.TokenFileds) time.Time); ok {
		r2 = rf(ctx, tokenFields)
	} else {
		r2 = ret.Get(2).(time.Time)
	}

	if rf, ok := ret.Get(3).(func(context.Context, auth.TokenFileds) error); ok {
		r3 = rf(ctx, tokenFields)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// NewTokenService creates a new instance of TokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenService {
	mock := &TokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
