// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// TokenStorage is an autogenerated mock type for the TokenStorage type
type TokenStorage struct {
	mock.Mock
}

// SetToken provides a mock function with given fields: ctx, userId, token, expire
func (_m *TokenStorage) SetToken(ctx context.Context, userId string, token string, expire time.Duration) error {
	ret := _m.Called(ctx, userId, token, expire)

	if len(ret) == 0 {
		panic("no return value specified for SetToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, userId, token, expire)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTokenStorage creates a new instance of TokenStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenStorage {
	mock := &TokenStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
