// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	actor "github.com/Heater_dog/Vk_Intern/internal/actor"

	mock "github.com/stretchr/testify/mock"
)

// ActorsService is an autogenerated mock type for the ActorsService type
type ActorsService struct {
	mock.Mock
}

// InsertActor provides a mock function with given fields: _a0, _a1
func (_m *ActorsService) InsertActor(_a0 context.Context, _a1 actor.ActorInsert) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertActor")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, actor.ActorInsert) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, actor.ActorInsert) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, actor.ActorInsert) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewActorsService creates a new instance of ActorsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActorsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActorsService {
	mock := &ActorsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
