// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	actor "github.com/Heater_dog/Vk_Intern/internal/actor"

	mock "github.com/stretchr/testify/mock"
)

// ActorsRepository is an autogenerated mock type for the ActorsRepository type
type ActorsRepository struct {
	mock.Mock
}

// AddActor provides a mock function with given fields: ctx, _a1
func (_m *ActorsRepository) AddActor(ctx context.Context, _a1 actor.ActorInsert) (string, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddActor")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, actor.ActorInsert) (string, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, actor.ActorInsert) string); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, actor.ActorInsert) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActors provides a mock function with given fields: ctx
func (_m *ActorsRepository) GetActors(ctx context.Context) ([]actor.Actor, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActors")
	}

	var r0 []actor.Actor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]actor.Actor, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []actor.Actor); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]actor.Actor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewActorsRepository creates a new instance of ActorsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActorsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActorsRepository {
	mock := &ActorsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
