// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	actor_model "github.com/Heater_dog/Vk_Intern/internal/models/actor"

	actorfilm "github.com/Heater_dog/Vk_Intern/internal/models/actor_film"

	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ActorsService is an autogenerated mock type for the ActorsService type
type ActorsService struct {
	mock.Mock
}

// DeleteActor provides a mock function with given fields: _a0, userID
func (_m *ActorsService) DeleteActor(_a0 context.Context, userID uuid.UUID) error {
	ret := _m.Called(_a0, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(_a0, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActors provides a mock function with given fields: _a0
func (_m *ActorsService) GetActors(_a0 context.Context) ([]actorfilm.ActorFilms, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetActors")
	}

	var r0 []actorfilm.ActorFilms
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]actorfilm.ActorFilms, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []actorfilm.ActorFilms); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]actorfilm.ActorFilms)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertActor provides a mock function with given fields: _a0, actor
func (_m *ActorsService) InsertActor(_a0 context.Context, actor actor_model.ActorInsert) (string, error) {
	ret := _m.Called(_a0, actor)

	if len(ret) == 0 {
		panic("no return value specified for InsertActor")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, actor_model.ActorInsert) (string, error)); ok {
		return rf(_a0, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, actor_model.ActorInsert) string); ok {
		r0 = rf(_a0, actor)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, actor_model.ActorInsert) error); ok {
		r1 = rf(_a0, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateActor provides a mock function with given fields: contex, fileds
func (_m *ActorsService) UpdateActor(contex context.Context, fileds actor_model.UpdateActor) error {
	ret := _m.Called(contex, fileds)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, actor_model.UpdateActor) error); ok {
		r0 = rf(contex, fileds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewActorsService creates a new instance of ActorsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActorsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActorsService {
	mock := &ActorsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
