// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	user_model "github.com/Heater_dog/Vk_Intern/internal/models/user"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// SignIn provides a mock function with given fields: ctx, user
func (_m *UserService) SignIn(ctx context.Context, user user_model.UserLogin) (string, string, time.Time, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 string
	var r1 string
	var r2 time.Time
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, user_model.UserLogin) (string, string, time.Time, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user_model.UserLogin) string); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, user_model.UserLogin) string); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, user_model.UserLogin) time.Time); ok {
		r2 = rf(ctx, user)
	} else {
		r2 = ret.Get(2).(time.Time)
	}

	if rf, ok := ret.Get(3).(func(context.Context, user_model.UserLogin) error); ok {
		r3 = rf(ctx, user)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
