

server_listen:
  ip: 0.0.0.0
  port: 8080

postgre_settings:
  host: postgre
  port: 5432
  database: films_database
  username: postgres
  password: 123

redis_settings:
  host: redis
  port: 6379
  password: 456
  token_expiration_days: 30

password_key: 123
